version: '2'
services:
  elasticsearch:
    image: "elasticsearch:2.4.1"
    volumes:
     - $PWD/es_data:/usr/share/elasticsearch/data
     - $PWD/es_config:/usr/share/elasticsearch/config
    ports:
     - "9200:9200"
     - "9300:9300"
  kibana:
    image: "kibana:4.6.4"
    ports:
     - "5601:5601"
    depends_on:
     - elasticsearch
    links:
     - elasticsearch
  neo4j:
    image: "neo4j:3.1.4"
    volumes:
     - $PWD/neo4j_data:/data
     - $PWD/neo4j_plugins:/var/lib/neo4j/plugins
     - $PWD/neo4j_conf:/var/lib/neo4j/conf
    ports:
     - "7474:7474"
     - "7687:7687"
    depends_on:
     - elasticsearch
    links:
     - elasticsearch
    environment:
     - NEO4J_AUTH=none
  elasticsearch-head:
    image: "mobz/elasticsearch-head:2"
    ports:
     - "9100:9100"
    depends_on:
     - elasticsearch
    links:
     - elasticsearch
