#! /bin/bash 
###########################################
# Start Elastic Search Service in Docker
# Docker Image https://hub.docker.com/r/_/elasticsearch/
###########################################

# constants
baseDir=$(cd `dirname "$0"`;pwd)
# functions

# main 
[ -z "${BASH_SOURCE[0]}" -o "${BASH_SOURCE[0]}" = "$0" ] || return
set -x
cd $baseDir
docker run --rm -it --name elasticsearch \
    -p 9200:9200 \
    -p 9300:9300 \
    -v "$PWD/esdata":/usr/share/elasticsearch/data \
    elasticsearch:latest
