#! /bin/bash 
###########################################
# Start Elastic Search Service in Docker
# Docker Image https://hub.docker.com/r/_/elasticsearch/
###########################################

# constants
baseDir=$(cd `dirname "$0"`;pwd)
. $baseDir/util.sh

# functions
function main(){
    docker run $* --name elasticsearch \
    -v "$PWD/esdata":/usr/share/elasticsearch/data \
    -p 9200:9200 \
    -p 9300:9300 elasticsearch:latest
}

# main 
[ -z "${BASH_SOURCE[0]}" -o "${BASH_SOURCE[0]}" = "$0" ] || return
cd $baseDir
if [ "$#" -eq  "0" ]
then
    printUsage
elif [ "$*" = "-t" ]
then
    main -it --rm
elif [ "$*" = "-d" ]
then
    main -d
else
    printUsage
fi