#! /bin/bash 
###########################################
# Start Kibana Service in Docker
# Docker Image https://hub.docker.com/r/_/kibana/
###########################################

# constants
baseDir=$(cd `dirname "$0"`;pwd)
. $baseDir/util.sh

# functions

function main(){
    docker run --name kibana \
        --link elasticsearch:elasticsearch \
        -p 5601:5601 \
        $* kibana:latest
}

# main 
[ -z "${BASH_SOURCE[0]}" -o "${BASH_SOURCE[0]}" = "$0" ] || return
cd $baseDir
if [ "$#" -eq  "0" ]
then
    printUsage
elif [ "$*" = "-t" ]
then
    main -t -i --rm
elif [ "$*" = "-d" ]
then
    main -d
else
    printUsage
fi